### ISSUE TITLE
Typo in Listing 9.4

### ISSUE THREAD

**Issue by jasonbarrows** [htmljenn/Teach-Yourself-Bootstrap-Code-Samples#1]
Hi Jennifer,

There is an additional **div** around the email input in the above listing as follows:

``` html
<form action="#" class="form-inline">
    <div class="form-group">
        <label for="email">Email Address</label>
        <div>
            <input type="email" required id="email" placeholder="Email Address" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" required id="password" placeholder="Password" class="form-control">
    </div>
    <div class="checkbox">
        <label>
            <input type="checkbox"> Remember me
        </label>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
</form>
    <div class="checkbox">
        <label>
            <input type="checkbox"> Remember me
        </label>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
</form>
```

Thanks for a great book, I am learning how to use bootstrap much more effectively.

Regards,
Jason

**Comment by htmljenn** [comment]
Thanks. It's not exactly a typo, just an extra tag. I do that sometimes to give myself more hooks for styling with the CSS. Forms can be especially difficult to style so putting a &lt;div&gt; tag around all the fields lets me style that without worrying if there's a button, input, or select field inside. 

But thanks for pointing it out.

**Comment by jasonbarrows** [comment]
Hi Jennifer,

Apologies, you are quite right, the extra tag doesn’t affect the layout.

Initially I thought it was the reason my inline form had extra margin/padding, but later discovered it was something else that was causing the issue.

Regards,
Jason

**Comment by htmljenn** [comment]
yeah, forms are a pain at times. but with Bootstrap you're getting a reset stylesheet too, so the divs shouldn't add extra space. Although I admit I haven't looked at that in a while, so they might.
